### ISSUE TITLE
Fail to install kftray with brew

### ISSUE THREAD

**Issue by emouty** [hcavarsan/kftray#191]
**Describe the bug**
When running ` brew install --HEAD kftray`, I get 

```
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Fetching hcavarsan/kftray/kftray
==> Cloning https://github.com/hcavarsan/kftray.git
Updating /home/emouty/.cache/Homebrew/kftray--git
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
HEAD is now at fcfd966 chore: upgrade github actions dependencies (#190)
==> Installing kftray from hcavarsan/kftray
==> npm install -ddd --global --build-from-source --cache=/home/emouty/.cache/Homebrew/npm_cache --prefix=/home/linuxbrew/.linuxbrew/Cellar/kftray/HEAD-fcfd966/libexec /tmp/kftray-20240404-695060-zhmdkg/kftray-0.9.0.tgz
==> npm install pnpm
==> npm install
==> npm run tauri build -b appimage
Last 15 lines from /home/emouty/.cache/Homebrew/Logs/kftray/04.npm:
dist/assets/logo-B2zb5TmM.png   490.17 kB
dist/assets/index-Cx9_4Dlo.css    0.78 kB │ gzip:   0.40 kB
dist/assets/index-BH620F1G.js   784.31 kB │ gzip: 248.37 kB

(!) Some chunks are larger than 600 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 2.67s
error: unexpected argument 'appimage' found

Usage: cargo build [OPTIONS]

For more information, try '--help'.
       Error failed to build app: failed to build app

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/hcavarsan/homebrew-kftray/issues
```

**Desktop (please complete the following information):**
 - OS: Fedora 39

**Comment by hcavarsan** [comment]
hey @emouty , ill install a Fedora VM and try to debug and fix this. i'll let you know! thx for the feedback.

**Comment by hcavarsan** [comment]
@emouty i just pushed a fix in the brew formula, can you check if it's ok now?

**Comment by emouty** [comment]
Hello, thanks for the quick responses, the command is fixed but it seems that they are some dependencies missing :

```
==> npm run tauri build -- -b appimage
Last 15 lines from /home/emoutymbo/.cache/Homebrew/Logs/kftray/04.npm:
      - /home/linuxbrew/.linuxbrew/opt/zlib/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/sqlite/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/xz/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/libedit/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/krb5/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/libtirpc/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/libnsl/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/expat/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/libffi/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/libxcrypt/lib/pkgconfig
      - /home/linuxbrew/.linuxbrew/opt/python@3.12/lib/pkgconfig

  HINT: you may need to install a package such as javascriptcoregtk-4.0, javascriptcoregtk-4.0-dev or javascriptcoregtk-4.0-devel.

       Error failed to build app: failed to build app
```

**Comment by hcavarsan** [comment]
hey @emouty,

sorry for the delay, just a heads-up: I was able to replicate the issue in my homelab running Fedora 39, and I've managed to solve a few steps, but I'm still working on some final adjustments.

I'll let you know as soon as I have an update!

**Comment by hcavarsan** [comment]
I created a new formula named kftray-linux for Linux and updated the installation section in the readme: [kftray Readme](https://github.com/hcavarsan/kftray?tab=readme-ov-file#-installation).

Note: To overcome a GTK limitation in Linux, you must activate the appindicator GNOME extension. Here is a video demonstrating kftray working in Fedora 39: 


https://github.com/hcavarsan/kftray/assets/30353685/0f8bd881-caff-4be8-8c57-5eef8919fab8


can you check if it's working?

**Comment by emouty** [comment]
Thanks its working, now ! The only issue remaining is that  the position of the window seems to be a bit random when I have multiple display connected. Sometimes its below the task bar on my main screen other times its on one of my secondary screen even though I don't have a task bar there. 

( We could close the this issues and see this in another one)

![image](https://github.com/hcavarsan/kftray/assets/16755668/a88a3cba-4579-4d27-b7fc-5792944d0f6f)

**Comment by hcavarsan** [comment]
hey, thx for the headsup!

let's keep this issue open...  im currently working on this code: [link](https://github.com/hcavarsan/kftray/pull/199) and will have it fixed soon!

**Comment by hcavarsan** [comment]
@emouty 
i've released the new version: https://github.com/hcavarsan/kftray/releases/tag/v0.9.7

now the app get the window position based on the mouse click. it worked in my tests; however, I couldn't replicate it on dual monitors...

and Wayland have some restrictions that X11 doesn't have, (eg to get the state from devices like mouse, keyboard etc..)

could you test it again and see if the window position is correct now?

**Comment by hcavarsan** [comment]
@emouty did you get a chance to test the latest release (v0.9.7) looking forward to your feedback.

**Comment by emouty** [comment]
Sadly no I'm away until mid may, I'll test it when I get back 🙂

**Comment by hcavarsan** [comment]
Ok @emouty, no problem. thanks.

**Comment by emouty** [comment]
I've tested it with v0.10.2 and window position is still wrong. Here is how my monitors are setup :
![image](https://github.com/hcavarsan/kftray/assets/16755668/1cfd3c78-e8de-4c87-9ed0-1743c2cf3cf5)

We end up having krew window between all 3 monitors :sweat_smile: 
![image](https://github.com/hcavarsan/kftray/assets/16755668/5af29262-4341-4eda-83b0-9fa5820ec8ea)

**Comment by hcavarsan** [comment]
hey @emouty, sorry,  It is quite difficult to adjust the window position on Linux. I have modified the library I use to get the mouse position and tested it with a monitor setup similar to yours, and it worked here on Fedora 39. Could you please test it to see if it is okay now? The version is: https://github.com/hcavarsan/kftray/releases/tag/v0.10.3

**Comment by hcavarsan** [comment]
Hello @emouty, I spent some time thinking about this, and I I found a way to solve it! 

Check out the video below. In the new version of [kftray v0.11.0](https://github.com/hcavarsan/kftray/releases/tag/v0.10.3), I implemented a new feature to move the window and also save the position state, so now you can choose the position that works best for you.

It's quite complicated to maintain app consistency across different platforms, especially on Linux, so I made this to be flexible and adjustable for the user until we find a better alternative :)

Can you test the new version and see if it works better?

Thank you, I hope this helps ;)

demo video:

https://github.com/hcavarsan/kftray/assets/30353685/4734c6a6-6d43-4c50-83ce-0a506ddd3d07

**Comment by emouty** [comment]
Hello, Yes this tweak fixes the window placement issue ! Thanks  for everything :)

**Comment by hcavarsan** [comment]
awesome! glad it worked out. thx for pointing out those inconsistencies, it really helps make the app better :) if u spot anything else weird, please let me know :)
